#!/usr/bin/env bash
# transfers a file from our client to a server

if [[ $# -lt 4 ]]
then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHosktKeyChecking=off -i "$4" "$1" "$3@$2:/home/$3"
fi
