#!/usr/bin/env bash
# install nginx server
# curl ip/ should return Hello World!

if [[ $EUID -ne 0 ]]
then
    echo 'Must be root user' 1>&2
    exit 1
fi 


# update your repo and then upgrade
if apt-get update -y && apt-get -y upgrade
then
    # install nginx
    apt install nginx
else
    echo "Update failed" 1>&2
    exit 1
fi

# create an index.html file in /var/www/html
echo "Hello World!" > /var/www/html/index.html

if ! service nginx restart
then
    echo "Failed to start Nginx" 1>&2
    exit 1
fi
