#!/usr/bin/env bash
# configure nginx server so that redirect_me is redirecting to another page

# ensure the script is run as root
if [[ $EUID -ne 0 ]]
then
    echo "You must be root user" 1>&2
    exit 1
fi

# update apt
if apt-get update
then
    echo "apt updated sucessfully"

    # install nginx
    if apt-get -y install nginx
    then
        echo "nginx installed sucessfully"
    else
        echo "nginx installation failed :(" 1>&2
        exit 1
    fi

else
    echo "apt not updated" 1>&2 
    exit 1
fi

# appends a rewrite to youtube.com
sed -i '/^root/a\\trewrite ^/redirect_me/?$ https://youtube.com permanent;'  /etc/nginx/sites-enabled/default

# reload configs
if nginx -s reload
then
    echo "reload sucessful"
else
    echo "nginx reload failed" 1>&2 
    exit 1
fi
