#!/usr/bin/env bash
# configure nginx server so that redirect_me is redirecting to another page


# update apt
apt-get update
apt-get -y install nginx

# create index.html
echo "Hello World!" > /var/www/html/index.html

# appends a rewrite to youtube.com
sed -i '/^\troot/a\\trewrite ^/redirect_me/?$ https://youtube.com permanent;'  /etc/nginx/sites-enabled/default

# reload configs
service nginx restart
