#!/usr/bin/env bash
# install and configure haproxy as a load balancer

apt-get update
apt-get install --no-install-recommends -y software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.9 -y
# install haproxy
apt-get -y install haproxy=2.9\*

# create a copy of the default haproxy config
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.old

# enable Haproxy to be started by the init script
echo "ENABLED=1" >> /etc/default/haproxy

echo -e "\nfrontend haproxy_server
\tbind *:80
\tdefault_backend nginx_servers\n
backend nginx_servers
\tbalance roundrobin
\tserver 530458-web-01 18.234.129.162:80 check
\tserver 530458-web-02 100.26.120.72:80 check" >> /etc/haproxy/haproxy.cfg

# restart haproxy
service haproxy restart
