#!/usr/bin/env bash
# Fizzbuzz

n=1

while [ $n -le 100 ]
do
    if [ $((n % 3)) -eq 0 ] && [ $((n % 5)) -eq 0 ]
    then
        echo "FizzBuzz"
        ((n++))
    elif [ $((n % 3)) -eq 0 ]
    then
        echo "Fizz"
        ((n++))
    elif [ $((n % 5)) -eq 0 ]
    then
        echo "Buzz"
        ((n++))
    else
        echo "$n"
        ((n++))
    fi
done
