#!/usr/bin/env bash
# loops from 1 to 10

var="Best School"
badLuck="bad luck"
goodLuck="good luck"
count=1

while [ $count -le 10 ];
do
    if [ $count -eq 4 ];
    then
        echo "$badLuck"
    elif [ $count -eq 8 ];
    then
        echo "$goodLuck"
    else
        echo "$var"
    fi
    ((count++))
done